version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    ignore:
      - legacy/**
    schedule:
      interval: "weekly"
    open-pull-requests: true
